### ISSUE TITLE
Add support for non-empty volumes

### ISSUE THREAD

**Issue by gadkins** [UffizziCloud/uffizzi_core#14]
We should support mounting [non-empty volumes](https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes) from the host environment. For example:

```
volumes:
    # Path on the host, relative to the Compose file
    - ./cache:/tmp/cache

    # Named volume
    - datavolume:/var/lib/mysql
```

Note: Do not try to support user-relative paths, e.g. `~/configs:/etc/configs/:ro`

**Relevant context:**
Since issue [`uffizzi_core#126`](https://github.com/UffizziCloud/uffizzi_app/issues/126#), we are supporting "empty" volumes, i.e. named volumes such as:

```
volumes:
    mydata:
    dbdata:
```

**Comment by gadkins** [comment]
We should add support for both [short and long syntax](https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes):

## Short syntax
```
volumes:
    # Path on the host, relative to the Compose file
    - ./cache:/tmp/cache
```

## Long syntax

From the long syntax we should support `source`, `target` and `read-only`.

```
services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - type: volume
        source: mydata
        target: /data
        volume:
          nocopy: true
      - type: bind
        source: ./static
        target: /opt/app/static

networks:
  webnet:

volumes:
  mydata:
```
