### ISSUE TITLE
Add Healthchecks (docker-compose.uffizzi.yml)

### ISSUE THREAD

**Issue by jpthurman** [UffizziCloud/uffizzi_core#8]
Add Uffizzi Compose support for healthcheck as define by Docker Compose here:
https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck

**Comment by 7R41N33** [comment]
uffizzi_controller PR:
https://github.com/UffizziCloud/uffizzi_controller/pull/5

**Comment by moklidia** [comment]
Compose file examples

```
services:
  redis:
    image: redis:latest

  hello-world:
    image: nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

x-uffizzi:
  continuous_preview:
    delete_preview_after: 10h

x-uffizzi-ingress:
  service: hello-world
  port: 80
```

Try with `test: ["CMD-SHELL", "curl", "-f", "http://localhost"]`, `test: "curl -f http://localhost"`, and `test: ["NONE"]

Check out the pods after deploy. If there is a healthcheck for a container it should appear as the 'liveness probe' property of the container. If the command is ``test: ["NONE"]`, the liveness prob shouldn't appear.

You can ping some existing websites (like http://google.com) for the check to succeed
