### ISSUE TITLE
Add Support for Volumes (docker-compose.uffizzi.yml)

### ISSUE THREAD

**Issue by jpthurman** [UffizziCloud/uffizzi_core#9]
Add Uffizzi Compose support for volumes (short and long syntax) as define by Docker Compose here:

https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes

**Comment by gadkins** [comment]
@zipofar Please see this example for generic ephemeral volumes. 

To support the `./healthchecks` example, assume:

- Volume type `ephemeral` (Generic). 
- Storage is local (Assume the volume to mount exists as a local directory in the git repo — similar to how we use config files).  
- Volume max size is 500MB

**Comment by zipofar** [comment]
@gadkins What do you think about this method of determining volumes:

For example user have compose file like this:

```
services:
  web:
    image: my_web_service

  nginx:
    image: nginx
    volumes:
      - ./images:/image_volumes
```

Our idea is that the user add rules like this:

```
x-uffizzi-volumes:
  - target_service: nginx
    source_service: web
    source_root_dir: /app
```
